### ISSUE TITLE
Unhandled Rejection (TypeError): ipify is not a function

### ISSUE THREAD

**Issue by jason-lex** [sindresorhus/ipify#16]
Hi when I copy the following code into my create-react-app

`const ipify = require('ipify');
 
(async () => {
    console.log(await ipify({useIPv6: false}));
    //=> '82.142.31.236'
})();`

I got the following error in the browser

> Unhandled Rejection (TypeError): ipify is not a function

and the error is pointing at `(async () => {` line

How do I fix this?

**Comment by sindresorhus** [comment]
The tests in this package are succeeding, so this is definitely a problem with your project or Create-React-App.
