### ISSUE TITLE
Allow parsing of `API_KEY` to get more info from geo.ipify.org/api [Suggestion]

### ISSUE THREAD

**Issue by obayomi96** [sindresorhus/ipify#21]
Thank you for this useful API. 
I was working with it and wanted to use the geo.ipify api to get more details like ISP, since ipify api does does not support this out of the box unless you use the geo.ipify api and create an apikey to add to the endpoint url.

- If possible, it would be cool to add the geo.ipify api endpint as well to the list of `constants` and call that if the user provides a valid api key to the `ipify()` function; e.g `ipify(API_KEY)`. 
- If this would be useful, if need be I can make this addition myself if contributions are accepted. I did not see a contribution guild file so I decided to raise an issue to ask the team. 

Cheers.

**Comment by sindresorhus** [comment]
Thanks for the suggestion. It's not something I plan to add to this package. I prefer to keep it simple and focused on only getting the IP address.
