### ISSUE TITLE
Make the ipify API location configurable

### ISSUE THREAD

**Issue by rbecheras** [sindresorhus/ipify#7]
This could be allow for example to set a location like `ipify.mycompany.com` where could be deployed a `ipify` fork, to ensure the API is always available.

**Comment by rbecheras** [comment]
We could use it by default:

const ipify = require('ipify');

```js
ipify((err, ip) => {
	console.log(ip);
	//=> '82.142.31.236'
});
```

or with a custom API location:


```js
const IPIFY_LOCATION = '109.65.85.41'
ipify(IPIFY_LOCATION, (err, ip) => {
	console.log(ip);
	//=> '82.142.31.236'
});
```

**Comment by rbecheras** [comment]
And fir the CLI:

    $ ipify
    82.142.31.236

or

    $ IPIFY_LOCATION=109.65.85.41
    $ ipify --api-location $IPIFY_LOCATION
    82.142.31.236

or with a short option (`-l` for 'location')

    $ IPIFY_LOCATION=109.65.85.41
    $ ipify -l $IPIFY_LOCATION
    82.142.31.236

**Comment by sindresorhus** [comment]
Done. I didn't add a short option as I don't really see the point. Short options are for things you write out manually each time. A custom endpoint is not that.
