### ISSUE TITLE
ie issue

### ISSUE THREAD

**Issue by mymonstermaggie** [sindresorhus/ipify#9]
this is awesome and very useful, however as soon as i add to my react project and import it i am no longer compatible with ie, works on all other browsers though. it gives a 1002 syntax error.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
